# HealthCare Dataset Analysis

In [2]:
#Importing libraries 

import pandas as pd
import numpy as np

In [3]:
# load the dataset 

data = pd.read_csv("../data/healthcare_dataset.csv")
data.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [4]:
data.shape

(55500, 15)

In [5]:
data.columns

Index(['Name', 'Age', 'Gender', 'Blood Type', 'Medical Condition',
       'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider',
       'Billing Amount', 'Room Number', 'Admission Type', 'Discharge Date',
       'Medication', 'Test Results'],
      dtype='object')

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

In [7]:
data.describe(include="int64")

                Age   Room Number
count  55500.000000  55500.000000
mean      51.539459    301.134829
std       19.602454    115.243069
min       13.000000    101.000000
25%       35.000000    202.000000
50%       52.000000    302.000000
75%       68.000000    401.000000
max       89.000000    500.000000

In [8]:
data['Date of Admission'] = pd.to_datetime(data['Date of Admission'])
data['Discharge Date'] = pd.to_datetime(data['Discharge Date'])

In [9]:
data.dtypes

Name                          object
Age                            int64
Gender                        object
Blood Type                    object
Medical Condition             object
Date of Admission     datetime64[ns]
Doctor                        object
Hospital                      object
Insurance Provider            object
Billing Amount               float64
Room Number                    int64
Admission Type                object
Discharge Date        datetime64[ns]
Medication                    object
Test Results                  object
dtype: object

### Converting Date of Admission and Discharge Date into datetime from object

In [10]:
#Checking the null values
data.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

no any missing values in columns

###  Univarite analysis

In [ ]:
data['Billing Amount'].describe()

count    55500.000000
mean     25539.316097
std      14211.454431
min      -2008.492140
25%      13241.224652
50%      25538.069376
75%      37820.508436
max      52764.276736
Name: Billing Amount, dtype: float64

min values seems to be in negative which is incorrect need to fix it

In [13]:
data["Age"].describe()

count    55500.000000
mean        51.539459
std         19.602454
min         13.000000
25%         35.000000
50%         52.000000
75%         68.000000
max         89.000000
Name: Age, dtype: float64

age group seems to be fine

### Categorical columns

In [14]:
data.columns

Index(['Name', 'Age', 'Gender', 'Blood Type', 'Medical Condition',
       'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider',
       'Billing Amount', 'Room Number', 'Admission Type', 'Discharge Date',
       'Medication', 'Test Results'],
      dtype='object')

In [20]:
for col in ['Gender','Medical Condition','Insurance Provider','Admission Type','Medication','Test Results','Billing Amount' ]:
     print(f"\n{col}")
     print(data[col].value_counts())
     print(data[col].value_counts(normalize=True).round(3)*100)

Gender
Gender
Male      27774
Female    27726
Name: count, dtype: int64
Gender
Male      50.0
Female    50.0
Name: proportion, dtype: float64

Medical Condition
Medical Condition
Arthritis       9308
Diabetes        9304
Hypertension    9245
Obesity         9231
Cancer          9227
Asthma          9185
Name: count, dtype: int64
Medical Condition
Arthritis       16.8
Diabetes        16.8
Hypertension    16.7
Obesity         16.6
Cancer          16.6
Asthma          16.5
Name: proportion, dtype: float64

Insurance Provider
Insurance Provider
Cigna               11249
Medicare            11154
UnitedHealthcare    11125
Blue Cross          11059
Aetna               10913
Name: count, dtype: int64
Insurance Provider
Cigna               20.3
Medicare            20.1
UnitedHealthcare    20.0
Blue Cross          19.9
Aetna               19.7
Name: proportion, dtype: float64

Admission Type
Admission Type
Elective     18655
Urgent       18576
Emergency    18269
Name: count, dtype: int64
Admission Type
Elective     33.6
Urgent       33.5
Emergency    32.9
Name: proportion, dtype: float64

Medication
Medication
Lipitor        11140
Ibuprofen      11127
Aspirin        11094
Paracetamol    11071
Penicillin     11068
Name: count, dtype: int64
Medication
Lipitor        20.1
Ibuprofen      20.0
Aspirin        20.0
Paracetamol    19.9
Penicillin     19.9
Name: proportion, dtype: float64

Test Results
Test Results
Abnormal        18627
Normal          18517
Inconclusive    18356
Name: count, dtype: int64
Test Results
Abnormal        33.6
Normal          33.4
Inconclusive    33.1
Name: proportion, dtype: float64

Billing Amount
Billing Amount
15928.714693    2
31585.608582    2
18134.582140    2
20802.903438    2
14238.317814    2
               ..
24747.348916    1
40657.582493    1
8441.147064     1
34934.284113    1
43303.425752    1
Name: count, Length: 50000, dtype: int64
Billing Amount
15928.714693    0.0
31585.608582    0.0
18134.582140    0.0
20802.903438    0.0
14238.317814    0.0
               ...
24747.348916    0.0
40657.582493    0.0
8441.147064     0.0
34934.284113    0.0
43303.425752    0.0
Name: proportion, Length: 50000, dtype: float64

# Bivariate Analysis

In [23]:
# Does age related to billing amount ?
data[['Age','Billing Amount','Room Number']].corr()

                     Age  Billing Amount  Room Number
Age             1.000000       -0.003832    -0.000720
Billing Amount -0.003832        1.000000    -0.002943
Room Number    -0.000720       -0.002943     1.000000

it shows that there is an huge negative correlation between the age , billing amount and room number. It seems that whatever age is yours it does not matter the billing amount it count be higher or lower . same as in room number you could be assigned to any room number that does not realte with you age

#### Categorical vs Numerical columns

In [25]:
# Which medical condition causes the most on average acutally ?
data.groupby('Medical Condition')['Billing Amount'].mean().sort_values(ascending=False)

Medical Condition
Obesity         25805.971259
Diabetes        25638.405577
Asthma          25635.249359
Arthritis       25497.327056
Hypertension    25497.095761
Cancer          25161.792707
Name: Billing Amount, dtype: float64

It seems that all the medical condition have similiar rate of billing amount in average of 25000 . There is no any High rate of billing condtion on average